language: python
sudo: false
dist: trusty
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- 2.7
- 3.4
- 3.5
- 3.6
env:
- GOOGLE_APPLICATION_CREDENTIALS=credentials.json
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_e3a216ea47b7_key -iv $encrypted_e3a216ea47b7_iv
  -in jgscm/tests/credentials.json.enc -out credentials.json -d; fi
- pip install --upgrade pip
- pip install pycodestyle codecov
install:
- pip install -e .
script:
- pycodestyle --max-line-length=100 .
- python -c "import jgscm"
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then coverage run --concurrency=multiprocessing -m unittest discover && coverage combine; fi
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then codecov; fi
notifications:
  email: false
